# NOTE(elsuizo:2018-04-21): este Makefile lo podemos utilizar
# con el arduino Makefile (AUR: arduino-mk) teniendo instalado
# arduino (sudo pacman -S arduino)

ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
ARDMK_VENDOR = archlinux-arduino

BOARD_TAG = uno

include $(ARDUINO)/Arduino.mk
