# Makefile for compile the arduino board from command line or better from neovim
ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
ARDMK_VENDOR = archlinux-arduino
BOARD_TAG = uno

ARDUINO_LIBS = Adafruit_PCD8544 SPI Adafruit_GFX
include $(ARDUINO)/Arduino.mk
