# Makefile for compile the arduino board from command line or better from neovim
ARDUINO_DIR = /home/elsuizo/.arduino_ide
ARDMK_DIR = /home/elsuizo/.arduino_mk
BOARD_TAG = uno
ARDUINO_LIBS = Adafruit_PCD8544 SPI Adafruit_GFX


include $(ARDMK_DIR)/Arduino.mk
