# Makefile for compile the arduino board from command line or better from neovim
ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
ARDMK_VENDOR = archlinux-arduino

BOARD_TAG = uno
# ARDUINO_LIBS = Time Ethernet SPI


include $(ARDUINO)/Arduino.mk
